language: node_js
node_js: node

before_script:
    - export NODE_ENV=production
    - export USE_CDN=USE_CDN

script:
    - npm run listdiff
    - npm run lint
    - npm run build

before_deploy:
    - touch ./build/.nojekyll

deploy:
    - provider: npm
      skip-cleanup: true
      email: $NPM_EMAIL
      api_key: $NPM_AUTH_TOKEN
      on:
          branch: master
          tags: false
      tag: next

    - provider: npm
      skip-cleanup: true
      email: $NPM_EMAIL
      api_key: $NPM_AUTH_TOKEN
      on:
          branch: master
          tags: true

    - provider: pages
      skip-cleanup: true
      github-token: $GITHUB_TOKEN
      local-dir: build
      on:
          branch: master

    - provider: pages
      skip-cleanup: true
      github-token: $GITHUB_TOKEN
      local-dir: build
      repo: lrc-maker/lrc-maker.github.io
      target-branch: master
      on:
          branch: master
          tags: true
