name: Build

on: [push, pull_request]

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: pnpm/action-setup@v2.2.2
            - uses: actions/setup-node@v3
              with:
                  node-version: "16"
                  cache: "pnpm"
            - run: pnpm i --ignore-scripts --frozen-lockfile

            - run: pnpm run "/check\:/"
            - run: pnpm run build
