name: Release https://lrc-maker.github.io and npm

on:
    push:
        tags:
            - "v*"

jobs:
    deploy:
        if: startsWith(github.ref, 'refs/tags/v')
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: pnpm/action-setup@v2.2.2
            - uses: actions/setup-node@v3
              with:
                  node-version: "16"
                  registry-url: "https://registry.npmjs.org"
                  cache: "pnpm"

            - run: pnpm i --ignore-scripts --frozen-lockfile

            - run: pnpm run "/check\:/"
            - run: make deploy

            - name: Publish NPM
              run: npm publish --ignore-scripts
              env:
                  NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}

            - name: Deploy to lrc-maker.github.io
              uses: peaceiris/actions-gh-pages@v3
              with:
                  personal_token: ${{ secrets.GHP_TOKEN }}
                  external_repository: lrc-maker/lrc-maker.github.io
                  publish_branch: master
                  publish_dir: ./build
                  force_orphan: true
